# Generated by Django 2.2.3 on 2019-07-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appels_sortants', '0003_auto_20190723_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prenom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historique',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels_sortants.Contact'),
        ),
    ]
