# Generated by Django 2.2.3 on 2019-07-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appels_sortants', '0005_auto_20190724_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Dernier appel',
            new_name='dernier_appel_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='cible_date',
            new_name='prochain_appel_date',
        ),
    ]
