# Generated by Django 2.2.3 on 2019-07-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_sortants', '0006_auto_20190724_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='contact',
        ),
        migrations.AlterField(
            model_name='contact',
            name='statut',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
