# Generated by Django 2.2.3 on 2019-07-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_sortants', '0010_auto_20190725_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='statut',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
