# Generated by Django 2.2.3 on 2019-07-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_sortants', '0012_auto_20190725_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='statut',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
