# Generated by Django 2.2.3 on 2019-07-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appels_sortants', '0015_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_site',
            new_name='site_personnel',
        ),
    ]
